package app.neurothrive.safehaven.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import app.neurothrive.safehaven.data.database.entities.EvidenceItem
import app.neurothrive.safehaven.data.repository.SafeHavenRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class CameraViewModel @Inject constructor(
    private val repository: SafeHavenRepository
) : ViewModel() {

    /**
     * Save evidence item after silent photo capture
     * File should already be encrypted by SilentCameraManager
     */
    fun saveEvidence(
        userId: String,
        encryptedFilePath: String,
        fileType: String = "image/jpeg",
        linkedIncidentId: String? = null,
        onSuccess: () -> Unit,
        onError: (Exception) -> Unit
    ) {
        viewModelScope.launch {
            try {
                val evidence = EvidenceItem(
                    id = UUID.randomUUID().toString(),
                    userId = userId,
                    encryptedFilePath = encryptedFilePath,
                    fileType = fileType,
                    capturedAt = System.currentTimeMillis(),
                    linkedIncidentReportId = linkedIncidentId,
                    sha256Hash = null, // Generated by DocumentVerificationService if needed
                    thumbnailPath = null,
                    fileSizeBytes = 0L, // Update with actual size
                    isSynced = false,
                    createdAt = System.currentTimeMillis(),
                    updatedAt = System.currentTimeMillis()
                )

                repository.insertEvidenceItem(evidence)
                onSuccess()
            } catch (e: Exception) {
                onError(e)
            }
        }
    }

    /**
     * Get all evidence for gallery view
     */
    fun getAllEvidence(userId: String) = repository.getAllEvidenceItems(userId)
}
